### ISSUE TITLE
tic-tak-to-using python

### ISSUE THREAD

**Issue by anilfth** [anilfth/tic_tak_to_game_python#1]
gets get started guys ....
first start with readme file 
create one beautiful readme for this repo 
tech we are going to use is python and it lib like tkinter etc
Happy learing...

**Comment by nabeelraza-7** [comment]
If you can allow for PyQt5, it can be done in a matter of minutes. Please consider.

**Comment by vikky-10** [comment]
plz assign me and lets begin

**Comment by anilfth** [comment]
go a head @vikky-10

**Comment by Diptadip** [comment]
please assign me this

**Comment by Diptadip** [comment]
Please merge the PR #6
